import type { MetadataRoute } from "next";

/**
 * Web app manifest.
 *
 * The layout has advertised `appleWebApp.capable` for a while without a
 * manifest ever being served, so the install prompt could never fire and
 * Lighthouse's installability audit failed. Served at /manifest.webmanifest.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "CROUStillant",
    short_name: "CROUStillant",
    description:
      "Consultez les menus des restaurants universitaires CROUS de France et d'outre-mer.",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#ffffff",
    theme_color: "#ffffff",
    lang: "fr",
    dir: "ltr",
    categories: ["food", "education", "lifestyle"],
    // Chromium only offers the install once a 192px and a 512px icon are
    // declared. Generated by scripts/generate-pwa-icons.mjs.
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
